#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorAnalogInactive)
#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Sensor, S4,     HTAC,                sensorI2CCustom)
#pragma config(Motor,  motorA,          flag,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          jaw,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          nonee,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     fr,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     br,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     noone,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     none,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     bl,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     fl,            tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    armr,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    arml,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Make sure these drivers and "common.h" are present in *\Robomatter Inc\ROBOTC Development Environment\Includes
#include "hitechnic-gyro.h"
#include "hitechnic-irseeker-v2.h"
#include "hitechnic-accelerometer-float-xysimple.h"

int times;

float xcal,ycal,zcal;

float xacc = 0;
float yacc = 0;
float zacc = 0;
float a0 = 0;
float a1 = 0;
float a2 = 0;
float tm0 = 0;
float tm1 = 0;
float tm2 = 0;
float velx = 0;

/*task accelerometer()
{
	while(true)
	{
		HTACreadAllAxes(HTAC, xacc, yacc, zacc);

		xacc -= xcal;
		yacc -= ycal;
		zacc -= zcal;

		a0 = a1;
		a1 = a2;
		a2 = xacc;

		tm0 = tm1;
		tm1 = tm2;
		tm2 = time1[T1];

		if(time1[T1] > 40)
			velx = -(((a2*(tm0 - tm1)*(3*tm0 - tm1 - 2*tm2) + a1*(tm0 - tm2)*(3*tm0 - 2*tm1 - tm2) - a0*(tm1 - tm2)*(tm1 - tm2))*(tm1 - tm2))/(6*(tm0 - tm1)*(tm0 - tm2)));

		writeDebugStreamLine("%d,%d,%d,%d,%d",time1[T1],xacc,yacc,zacc,velx);
	}
}*/

task main()
{
	/*HTACreadAllAxes(HTAC, xcal, ycal, zcal);

	writeDebugStreamLine("t,x,y,z");
	time1[T1] = 0;
	StartTask(accelerometer);

	motor[fl] = -30;
	motor[fr] = 30;
	motor[bl] = -30;
	motor[br] = 30;

	wait1Msec(1000);

	motor[fl] = 0;
	motor[fr] = 0;
	motor[bl] = 0;
	motor[br] = 0;*/

	time1[T1] = 0;
	HTACreadAllAxes(HTAC, xcal, ycal);
	times = time1[T1];
}
